"""The text `derive_plant.py` writes into `p4f_newton/godot_plant.py`.

Kept in its own module because it is a Python file that contains a Python file. Nesting the template
inside the generator meant one level of quoting for the template and another for the f-strings that
fill it, and the generator was broken twice by that quoting alone - once producing a literal newline
inside a string literal, which does not fail until the generator next runs.
"""

from __future__ import annotations

TEMPLATE = '''"""Godot's ACTUAL per-bone actuator gains, measured - not the authored ones.

GENERATED by `isaac_lab_3/scripts/derive_plant.py` on {stamp}
from `{source}` at physics {physics_hz} Hz. Do not hand-edit; regenerate.

Godot's `PidController3D` uses the Tan-Liu-Turk Stable PD form and divides both gains by
`1 + Kd*dt/I + Kp*dt^2/I`. Isaac's `ImplicitActuatorCfg` applies the authored gains at full value,
so every policy trained before this table existed drove a joint several times stiffer than the one
it meets in Godot. Scaling BOTH stiffness and damping by the same factor reproduces Godot's plant,
because Godot divides both by the same denominator.

The factor is PER BONE, because the denominator divides by that bone's inertia. Measured spread here
is {spread}x - {low_bone} at {low_scale}, {high_bone} at {high_scale} - so a single averaged factor
would be wrong for almost every joint.

Verified against a step response rather than assumed: on `joint_Thigh_L:1` at 0.15 rad this table
alone puts Isaac's rise time at 33.3 ms against Godot's 33.3 ms. See `assets.py` for the residual
that remains (damping, which no scaling closes).

**Valid only at {physics_hz} Hz.** The denominator is a function of dt: raising the physics rate
collapses it toward 1 and moves Godot's effective gains up. Measured at 480 Hz the body-wide mean
rises from 0.15 to 0.44. If `physics_ticks_per_second` changes, regenerate.
"""

from __future__ import annotations

#: Physics rate (Hz) these factors were measured at. `assets.py` warns if the environment disagrees.
MEASURED_PHYSICS_HZ = {physics_hz}

#: Godot bone name -> the fraction of its authored gain Godot actually applies.
BONE_SPD_SCALE: dict[str, float] = {{
{rows}
}}

#: Godot bone name -> its parent bone, or None for the root. Mirrors ActiveRagdoll.tscn's ParentBone
#: wiring. `dummy_d6_rig.json` carries joints and gains but NO body graph, and Godot's gravity
#: feed-forward is defined over the distal chain, so the Isaac side needs this to reproduce it.
BONE_PARENT: dict[str, str | None] = {{
{parents}
}}

#: Godot bone name -> mass (kg), as Godot's own rigid bodies report it.
BONE_MASS: dict[str, float] = {{
{masses}
}}

#: Godot bone name -> its joint anchor in the bone's OWN frame (x, y, z).
#: The gravity feed-forward takes its lever arms about this point. Approximating it as the
#: bone/parent midpoint misplaces every lever arm, so it is measured rather than assumed.
BONE_PIVOT_LOCAL: dict[str, tuple[float, float, float]] = {{
{pivots}
}}

#: Godot bone name -> its actuator torque ceiling (N.m), as authored on the bone.
BONE_MAX_TORQUE: dict[str, float] = {{
{max_torques}
}}


def distal_chain(bone: str) -> list[str]:
    """`bone` and every bone below it, matching Godot's `ActiveBone.BuildDistalChain`.

    The gravity feed-forward at a joint holds up everything distal to it, not just the one link.
    """
    out = [bone]
    frontier = [bone]
    while frontier:
        current = frontier.pop()
        for child, parent in BONE_PARENT.items():
            if parent == current and child not in out:
                out.append(child)
                frontier.append(child)
    return out


def scale_for_joint(joint_name: str, default: float = 1.0) -> float:
    """Scale factor for an Isaac joint name such as ``joint_Thigh_L:0``.

    The D6 rig names every DOF ``joint_<Bone>:<axis>``, and Godot's `ActiveBone` applies one gain
    pair to the bone's whole 3D angular error, so all three axes of a bone share its factor.

    Returns `default` for an unmapped joint rather than raising, but `assets.py` treats a miss as an
    error: a joint silently left at full gain is the exact failure this table exists to prevent.
    """
    if not joint_name.startswith("joint_"):
        return default
    bone = joint_name[len("joint_"):].rsplit(":", 1)[0]
    return BONE_SPD_SCALE.get(bone, default)
'''
