namespace Physics4Fun.RL.MuJoCo;

/// <summary>
/// Byte offsets into MuJoCo's <c>mjModel</c> and <c>mjData</c>, for the P/Invoke bridge.
/// </summary>
/// <remarks>
/// <para><b>Generated by <c>mujoco_rig/gen_offsets.py</c> - do not hand-edit.</b> The offsets
/// are located empirically, by scanning each struct for the address of an array the Python
/// bindings already expose, because hand-computing C alignment silently produces plausible
/// wrong numbers: reading <c>mjModel</c> at 0/4/8 returned nq=52, nv=0, nu=51 against the true
/// 52/51/36.</para>
/// <para>Generated against MuJoCo 3.8.1. Regenerate after any upgrade;
/// <c>MjBridge</c> verifies them at load and refuses to run if they no longer agree.</para>
/// </remarks>
internal static class MjLayout
{
    /// <summary>MuJoCo version these offsets were generated against.</summary>
    public const string Version = "3.8.1";

    /// <summary>Offset of <c>mjModel.nq</c> (mjtSize, 8 bytes).</summary>
    public const int ModelNq = 0;
    /// <summary>Offset of <c>mjModel.nv</c> (mjtSize, 8 bytes).</summary>
    public const int ModelNv = 8;
    /// <summary>Offset of <c>mjModel.nu</c> (mjtSize, 8 bytes).</summary>
    public const int ModelNu = 16;
    /// <summary>Offset of <c>mjModel.nbody</c> (mjtSize, 8 bytes).</summary>
    public const int ModelNbody = 32;

    /// <summary>Offset of <c>mjModel.BodyMass</c> (pointer).</summary>
    public const int ModelBodyMass = 1888;
    /// <summary>Offset of <c>mjModel.JntQposadr</c> (pointer).</summary>
    public const int ModelJntQposadr = 2056;
    /// <summary>Offset of <c>mjModel.JntDofadr</c> (pointer).</summary>
    public const int ModelJntDofadr = 2064;
    /// <summary>Offset of <c>mjModel.BodyRootid</c> (pointer).</summary>
    public const int ModelBodyRootid = 1760;
    /// <summary>Offset of <c>mjData.Xpos</c> (pointer).</summary>
    public const int DataXpos = 161800;
    /// <summary>Offset of <c>mjData.Xquat</c> (pointer).</summary>
    public const int DataXquat = 161824;
    /// <summary>Offset of <c>mjData.Xipos</c> (pointer).</summary>
    public const int DataXipos = 161840;
    /// <summary>Offset of <c>mjData.Ctrl</c> (pointer).</summary>
    public const int DataCtrl = 161704;
    /// <summary>Offset of <c>mjData.Qpos</c> (pointer).</summary>
    public const int DataQpos = 161648;
    /// <summary>Offset of <c>mjData.Qvel</c> (pointer).</summary>
    public const int DataQvel = 161672;
    /// <summary>Offset of <c>mjData.XfrcApplied</c> (pointer).</summary>
    public const int DataXfrcApplied = 161728;
    /// <summary>Offset of <c>mjData.Cvel</c> (pointer).</summary>
    public const int DataCvel = 162216;
    /// <summary>Offset of <c>mjData.SubtreeCom</c> (pointer).</summary>
    public const int DataSubtreeCom = 161888;
}
